function [ekgPeaks, ibiInfo, ibiMeasures] = getEmptyBeatStructs()

 ekgPeaks = struct('fileName', NaN, 'subName', NaN, 'srate', NaN, ...
                   'ekg', NaN, 'peakFrames', NaN);
              
ibiInfo = struct('fileName', NaN, 'subName', NaN, ...
                 'fileMins', NaN, 'overallMeasures', NaN, ...
                 'blockMins', NaN, 'blockStepMins', NaN, 'blockMeasures', NaN);

ibiMeasures = struct('startMins', NaN, 'blockMins', NaN, 'numIBIs', NaN, ...
                  'meanHR', NaN, 'meanIBI', NaN, 'medianIBI', NaN', ...
                  'sdnn', NaN, 'sdsd', NaN, ...
                  'rmsdd', NaN, 'nn50', NaN, 'pnn50', NaN, ...
                  'totalPower', NaN, 'vlf', NaN, 'lf', NaN, ...
                  'hf', NaN, 'lhRatio', NaN);