function [ekgPeaks, rrInfo, rrMeasures] = getEmptyBeatStructs()

ekgPeaks = struct('fileName', NaN, 'srate', NaN, 'ekg', NaN, ...
    'peakFrames', NaN, 'lowAmplitudePeaks', NaN);
              
rrInfo = struct('fileName', NaN, 'fileMinutes', NaN, 'overallValues', NaN, ...
                 'blockMinutes', NaN, 'blockStepMinutes', NaN, 'blockValues', NaN);

rrMeasures = struct('startMinutes', NaN, 'blockMinutes', NaN, ...
                  'numRRs', NaN, 'numBadRRs', NaN, ...
                  'meanHR', NaN, 'meanRR', NaN, 'medianRR', NaN, ...
                  'trendSlope', NaN, 'SDNN', NaN, 'SDSD', NaN, ...
                  'RMSSD', NaN, 'NN50', NaN, 'pNN50', NaN, ...
                  'spectrumType', NaN, 'totalPower', NaN, ...
                   'VLF', NaN, 'LF', NaN,   'LFnu', NaN, ...
                   'HF', NaN, 'HFnu', NaN, 'LFHFRatio', NaN, ...
                   'PSD', NaN, 'F', NaN);        
                   