function ibiStats = getIBIStatsStruct()


ibiStats = struct('meanHR', NaN, 'meanIBI', NaN, 'medianIBI', NaN', ...
                  'sdnn', NaN, 'sdsd', NAN, ...
                  'rmsdd', NaN, 'nn50', NaN, 'pnn50', NaN, ...
                  'totalPower', NaN, 'vlf', NaN, 'lf', NaN, ...
                  'hf', NaN, 'lhRatio', NaN);